<?php

namespace ideup\pruebaTecnicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImagsViviendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagsViviendaRepository extends EntityRepository
{
}
