<?php

namespace ideup\pruebaTecnicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ViviendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViviendaRepository extends EntityRepository
{
}
