_homepage:
    pattern:  /vivienda
    defaults: { _controller: ideuppruebaTecnicaBundle:Hello:index }
    
vivienda_new:
  pattern: /vivienda/new
  defaults: {_controller: ideuppruebaTecnicaBundle:Default:new}
