parameters:
#    ideupprueba_tecnica.example.class: ideup\pruebaTecnicaBundle\Example

services:
#    ideupprueba_tecnica.example:
#        class: %ideupprueba_tecnica.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
